// THE ORDER IN HERE MATTERS!!
#include "Move.h"
#include "Piece.h"
#include "Board.h"
#include "Advantage.h"
#include "TranspostitionTable.h"
#include "Game.h"
#include "HeuristicBonuses.h"
#include "Move.cpp"
#include "Piece.cpp"
#include "Board.cpp"
#include "Advantage.cpp"
#include "TranspostitionTable.cpp"
#include "Game.cpp"
